<a href="https://colab.research.google.com/github/memrranmian/my-first-repo1/blob/main/ai_navtcc_navtcc_lab15_numpy_lec18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# numpy array (numerical phython)
# faster than series in panda data frame
#  offical help https://numpy.org/doc/stable/user/absolute_beginners.html

# pip install numpy

import numpy as np

a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [32]:
a=np.array([1,2,3,4,5,6])
print(a)
print(a[0])
a[0]

a[:3]
print(a)
a[3:]
print(a)
a[3:6]
print(a)


c=a.copy()


a[0]=10
print(a[:3])
print(a)


b=a[3:]
print(b)
b[0]=40
print(b)
print(a)

print('value of c array',c)


[1 2 3 4 5 6]
1
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[10  2  3]
[10  2  3  4  5  6]
[4 5 6]
[40  5  6]
[10  2  3 40  5  6]
value of c array [1 2 3 4 5 6]


In [43]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[1,3]) #print the element in row 1 n column 3 i.e. 8
print(a.shape)
print(len(a))
print(len(a.shape))
print(a.ndim)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
8
(3, 4)
3
2
2


In [33]:
x = np.array([[1,2,3],[4,5,6]], order='F')
print(x)

[[1 2 3]
 [4 5 6]]
